[package]
name = "dashu"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Zhong <cmpute@gmail.com>"]
description = "A library set of big numbers"
keywords = ["mathematics", "bignum"]
categories = ["mathematics", "no-std"]
repository = "https://github.com/cmpute/dashu"
homepage = "https://github.com/cmpute/dashu"
license = "MIT OR Apache-2.0"
rust-version = "1.61"

[dependencies]
# all crates under dashu will have the same major and minor version,
# but the patch version can be different.
dashu-base = { path = "./base", version = "0.1.0" }
dashu-int = { path = "./integer", version = "0.1.0" }
dashu-float = { path = "./float", version = "0.1.0" }
dashu-macros = { path = "./macros", version = "0.1.0" }

[workspace]
members = [
    "base",
    "benchmark",
    "integer",
    "float",
    "macros",
]
default-members = ["base", "integer", "float", "macros"]
