[package]
name = "dashu-macros"
version = "0.2.0"
authors = ["Jacob Zhong <cmpute@gmail.com>"]
edition = "2021"
description = "Procedure macros for creating big numbers"
keywords = ["mathematics", "numerics", "arbitrary-precision"]
categories = ["mathematics", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/cmpute/dashu"
homepage = "https://github.com/cmpute/dashu"
readme = "README.md"
rust-version = "1.61"

[package.metadata.docs.rs]
all-features = true

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1"

[dependencies.dashu-int]
path = "../integer"
version = "0.2.0"

[dependencies.dashu-float]
path = "../float"
version = "0.2.0"
