[package]
name = "dashu-macros"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Zhong <cmpute@gmail.com>"]
description = "Procedure macros to create big numbers"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1"

[dependencies.dashu-int]
path = "../integer"
version = "0.1.1"
